### PR TITLE
Move channels overlay into JFrog Addon

### PR DESCRIPTION
**Pull request by johnsca**
Needs review from @shrajfr12 and I haven't tested it yet (starting it now, will update)

### CODE REVIEW

**Comment by shrajfr12** [comment]
But I will also try to with the these changes and let you know

**Comment by shrajfr12** [comment]
I ran in my local environment without passing bundle-add channels.yaml since it is now in before-config (I had to chmod +x before-config as I manually created the file and it did not hv execute permissions) and install went through fine and verified from kubectl get nodes and confirmed it shows 1.9.6.  So looks good and thanks for updating README as well to reflect this change.

**Comment by johnsca** [comment]
Yes, that was the error, "could not find a ready tiller pod."  So it sounds like you're ok with this approach, so I'll go ahead and merge and update edge.

Is there anything I can do to help address the occasional missing tiller issue?

**Comment by johnsca** [comment]
This is now available in edge (rev 998)

**Pull request merged**
